---
- name: Common Tool Setup On all the servers
  hosts: appsrvgrp
  become: yes
  vars:
    tom_url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.82/bin/apache-tomcat-9.0.82.tar.gz
  tasks:
    - name: Install JDK on Redhat-Distro
      yum:
        name: java-1.8.0-openjdk
        state: present
      when: ansible_distribution == "RedHat"

    - name: Install JDK on Ubuntu 
      apt: 
        name: openjdk-8-jdk 
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Download Tomcat Tar Ball/Binaries
      get_url:
        url: "{{tom_url}}"
        dest: /tmp/tomcat-9.tar.gz

    - name: Add tomcat group
      group:
        name: tomcat
        state: present
    
    - name: Add tomcat user
      user:
        name: tomcat
        group: tomcat
        shell: /bin/nologin
        home: /usr/local/tomcat9
    
    - file:
        path: /tmp/tomcat8
        state: directory
    
    - name: Extract tomcat
      unarchive:
        src: /tmp/tomcat-9.tar.gz
        dest: /tmp/tomcat9/
        remote_src: yes
        list_files: yes
      register: unarchive_info

    - debug:
        msg: "{{unarchive_info.files[0].split('/')[0]}}"
    
    - name: Synchronize /tmp/tomcat8/tomcat_cont /usr/local/tomcat8.
      synchronize:
        src: "/tmp/tomcat9/{{unarchive_info.files[0].split('/')[0]}}/"
        dest: /usr/local/tomcat9/
      delegate_to: "{{ inventory_hostname }}"

    - name: Change ownership of /usr/local/tomcat9
      file:
        path: /usr/local/tomcat9
        owner: tomcat
        group: tomcat
        recurse: yes
    
    - name: Setup tomcat SVC file on Redhat-Distro
      template:
         src: templates/redhat-svcfile.j2
         dest: /etc/systemd/system/tomcat.service
         mode: "a+x"
      when: ansible_distribution == 'RedHat'
    
    - name: Setup tomcat SVC file on ubuntu 16 and 18
      template:
         src: templates/ubuntu16-svcfile.j2
         dest: /etc/systemd/system/tomcat.service
         mode: "a+x"
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version >= '20.04'
    
    - name: just force systemd to reread configs (2.4 and above)
      systemd:
        daemon_reload: yes 
    
    - name: Start & Enable TOmcat 9
      service:
        name: tomcat
        state: started
        enabled: yes